default:
	just neural-light

performance:
	cargo run --release --features demo -- PERFORMANCE

neural-light:
	cargo run --release --features demo -- NEURAL_LIGHT

neural:
	cargo run --release --features demo -- NEURAL
